[package]
name = "luna-unfil"
version = "0.1.0"
authors = ["Ell <alan@cattes.us>"]
edition = "2018"

[lib]
name = "libfil"
path = "src/lib.rs"

[[bin]]
name = "unfil"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
byteorder = "1"